### ISSUE TITLE
Milestone 3 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-2#139]
## Rubric
- 21 / 25: Analysis code is abstracted to four (or more) scripts which take command line arugments and save analysis artifacts (e.g., figures and data for tables).
- 19 / 25: Report is written in a literate code document, and the code in the literate code document primarily functions to source analysis artifacts and format the document.
- 23 / 25: A data analysis pipeline written in GNU Make exists, and works to run the analysis from beginning to end, as well as to clean up the analysis
- 2 / 2: Dependencies have been updated (so it include the test libraries)
- 2 / 2: Project file and directory structure organization
- 2 / 2: GitHub Project board
- 2 / 2: GitHub Issue Milestones
- 2 / 2: Follows GitHub flow version control workflow
- 0 / 2: GitHub release
- 1 / 13: Analysis can be run reproducibly using documentation provided in the README.

## Commonly provided feedback

Recommended to open an issue in the project's repository to provide this feedback so students can act on it.
In milestone 4, these things will be regraded as part of the final grade for the project.
Bolded points indicate how many points should be taken off the rubric for each of these.
These numbers do not need to be included in the GitHub issue.

Text to copy and paste into GitHub issue before providing specific comments:

*Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Analysis code is abstracted to four (or more) scripts which take command line arguments and save analysis artifacts (e.g., figures and data for tables).

- [ ] One or more scripts are not well organized **- 4**

All of the scripts contain problems like:

- Weird block of empty lines
- Commented out code
- Long main function that could be reduced by abstracting code

### Report is written in a literate code document, and the code in the literate code document primarily functions to source analysis artifacts and format the document.

- [ ] The literate code document (R Markdown or Jupyter notebook) does not use markup language syntax to reference tables and figures so that the correct table and figure numbers are automatically used **- 4**

- [ ] The literate code document (R Markdown or Jupyter notebook) does not use code to automatically update inline values generated from the analysis that are presented in the narrated text of the document but it does not work correctly or a few missing cases. **- 2**

For instance, "From our graph above we can see that our accuracy peaks at around 12-13 neighbors".

### A data analysis pipeline written in GNU Make exists, and works to run the analysis from beginning to end, as well as to clean up the analysis

- [ ] Target `all` could be simplified by writing something like `all: <report_target>`. **- 2**

### GitHub release

- [ ] There is no link nor instructions to access the GitHub release for milestone 3. **-2**

There is only a link to **all of the releases**. Based my analysis on `v0.21.0`.

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing). **-2**

What exactly is the first way to run the analysis? The one that uses docker. For instance, it doesn't tell me how to use `make all`

- [ ] Could not reproducibly run the analysis fully because I got an error on running `make all`. **-5**

It occurred in the `Rscript src/modeling.r --train=data/processed/training.csv --out_dir=results` part

```
# git clone https://github.com/DSCI-310/DSCI-310-Group-2.git
Cloning into 'DSCI-310-Group-2'...
remote: Enumerating objects: 1406, done.
remote: Counting objects: 100% (1406/1406), done.
remote: Compressing objects: 100% (1009/1009), done.
remote: Total 1406 (delta 763), reused 805 (delta 344), pack-reused 0
Receiving objects: 100% (1406/1406), 1.67 MiB | 1.08 MiB/s, done.
Resolving deltas: 100% (763/763), done.
# cd DSCI-310-Group-2
# ls
CODE_OF_CONDUCT.md  CONTRIBUTING.md  Dockerfile  LICENSE.md  Makefile  R  README.md  data  doc  results  src  tests
# git checkout v0.21.0
Note: switching to 'v0.21.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 7b6784b Merge pull request #90 from DSCI-310/rpeng35-patch-2
# ls
CODE_OF_CONDUCT.md  CONTRIBUTING.md  Dockerfile  LICENSE.md  Makefile  R  README.md  data  doc  results  src  tests
# make all
Makefile:27: warning: overriding recipe for target 'results/box_hd.png'
Makefile:15: warning: ignoring old recipe for target 'results/box_hd.png'
Makefile:27: warning: overriding recipe for target 'results/distribution_of_diagnosis.png'
Makefile:15: warning: ignoring old recipe for target 'results/distribution_of_diagnosis.png'
Makefile:27: warning: overriding recipe for target 'results/variable_correlation.png'
Makefile:15: warning: ignoring old recipe for target 'results/variable_correlation.png'
Rscript src/download_data.r --url=https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data --out_file=data/raw/cleveland_raw.csv
── Attaching packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.1 ──
✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.6     ✔ dplyr   1.0.8
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
Warning messages:
1: package ‘tidyr’ was built under R version 4.1.2
2: package ‘readr’ was built under R version 4.1.2
3: package ‘dplyr’ was built under R version 4.1.2
── Attaching packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidymodels 0.1.4 ──
✔ broom        0.7.12     ✔ rsample      0.1.1
✔ dials        0.1.0      ✔ tune         0.2.0
✔ infer        1.0.0      ✔ workflows    0.2.6
✔ modeldata    0.1.1      ✔ workflowsets 0.2.1
✔ parsnip      0.2.1      ✔ yardstick    0.0.9
✔ recipes      0.2.0
── Conflicts ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()
• Learn how to get started at https://www.tidymodels.org/start/
Warning messages:
1: package ‘broom’ was built under R version 4.1.2
2: package ‘dials’ was built under R version 4.1.2
3: package ‘parsnip’ was built under R version 4.1.2
4: package ‘recipes’ was built under R version 4.1.2
5: package ‘tune’ was built under R version 4.1.2
6: package ‘workflows’ was built under R version 4.1.2
7: package ‘workflowsets’ was built under R version 4.1.2
Warning message:
package ‘docopt’ was built under R version 4.1.2
Registered S3 method overwritten by 'GGally':
  method from
  +.gg   ggplot2

Attaching package: ‘rlang’

The following objects are masked from ‘package:purrr’:

    %@%, as_function, flatten, flatten_chr, flatten_dbl, flatten_int,
    flatten_lgl, flatten_raw, invoke, splice

Warning message:
package ‘rlang’ was built under R version 4.1.2
Rscript src/preprocess_data.r --input=data/raw/cleveland_raw.csv --out_dir=data/processed
── Attaching packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.1 ──
✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.6     ✔ dplyr   1.0.8
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
Warning messages:
1: package ‘tidyr’ was built under R version 4.1.2
2: package ‘readr’ was built under R version 4.1.2
3: package ‘dplyr’ was built under R version 4.1.2
Warning message:
package ‘docopt’ was built under R version 4.1.2
── Attaching packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidymodels 0.1.4 ──
✔ broom        0.7.12     ✔ rsample      0.1.1
✔ dials        0.1.0      ✔ tune         0.2.0
✔ infer        1.0.0      ✔ workflows    0.2.6
✔ modeldata    0.1.1      ✔ workflowsets 0.2.1
✔ parsnip      0.2.1      ✔ yardstick    0.0.9
✔ recipes      0.2.0
── Conflicts ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()
• Search for functions across packages at https://www.tidymodels.org/find/
Warning messages:
1: package ‘broom’ was built under R version 4.1.2
2: package ‘dials’ was built under R version 4.1.2
3: package ‘parsnip’ was built under R version 4.1.2
4: package ‘recipes’ was built under R version 4.1.2
5: package ‘tune’ was built under R version 4.1.2
6: package ‘workflows’ was built under R version 4.1.2
7: package ‘workflowsets’ was built under R version 4.1.2
Registered S3 method overwritten by 'GGally':
  method from
  +.gg   ggplot2

Attaching package: ‘rlang’

The following objects are masked from ‘package:purrr’:

    %@%, as_function, flatten, flatten_chr, flatten_dbl, flatten_int,
    flatten_lgl, flatten_raw, invoke, splice

Warning message:
package ‘rlang’ was built under R version 4.1.2

Attaching package: ‘magrittr’

The following object is masked from ‘package:rlang’:

    set_names

The following object is masked from ‘package:purrr’:

    set_names

The following object is masked from ‘package:tidyr’:

    extract

Warning message:
package ‘magrittr’ was built under R version 4.1.3
Rscript src/modeling.r --train=data/processed/training.csv --out_dir=results
── Attaching packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.1 ──
✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.6     ✔ dplyr   1.0.8
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
Warning messages:
1: package ‘tidyr’ was built under R version 4.1.2
2: package ‘readr’ was built under R version 4.1.2
3: package ‘dplyr’ was built under R version 4.1.2
── Attaching packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidymodels 0.1.4 ──
✔ broom        0.7.12     ✔ rsample      0.1.1
✔ dials        0.1.0      ✔ tune         0.2.0
✔ infer        1.0.0      ✔ workflows    0.2.6
✔ modeldata    0.1.1      ✔ workflowsets 0.2.1
✔ parsnip      0.2.1      ✔ yardstick    0.0.9
✔ recipes      0.2.0
── Conflicts ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()
• Dig deeper into tidy modeling with R at https://www.tmwr.org
Warning messages:
1: package ‘broom’ was built under R version 4.1.2
2: package ‘dials’ was built under R version 4.1.2
3: package ‘parsnip’ was built under R version 4.1.2
4: package ‘recipes’ was built under R version 4.1.2
5: package ‘tune’ was built under R version 4.1.2
6: package ‘workflows’ was built under R version 4.1.2
7: package ‘workflowsets’ was built under R version 4.1.2
Registered S3 method overwritten by 'GGally':
  method from
  +.gg   ggplot2
Warning message:
package ‘docopt’ was built under R version 4.1.2

Attaching package: ‘rlang’

The following objects are masked from ‘package:purrr’:

    %@%, as_function, flatten, flatten_chr, flatten_dbl, flatten_int,
    flatten_lgl, flatten_raw, invoke, splice

Warning message:
package ‘rlang’ was built under R version 4.1.2
x Fold1: preprocessor 1/1, model 1/1: Error in `check_outco...
x Fold2: preprocessor 1/1, model 1/1: Error in `check_outco...
x Fold3: preprocessor 1/1, model 1/1: Error in `check_outco...
x Fold4: preprocessor 1/1, model 1/1: Error in `check_outco...
x Fold5: preprocessor 1/1, model 1/1: Error in `check_outco...
Error in `estimate_tune_results()`:
! All of the models failed. See the .notes column.
Backtrace:
    ▆
 1. ├─global main(opt[["--train"]], opt[["--out_dir"]])
 2. │ └─... %>% collect_metrics()
 3. ├─tune::collect_metrics(.)
 4. └─tune:::collect_metrics.tune_results(.)
 5.   └─tune::estimate_tune_results(x)
 6.     └─rlang::abort("All of the models failed. See the .notes column.")
Warning message:
All models failed. See the `.notes` column.
Execution halted
make: *** [Makefile:19: results/accuracy_plot.png] Error 1
```

- [ ] Even after some non trivial debug, I got many other errors related to the report. **- 5**

Errors that I got while trying to run `Rscript -e "rmarkdown::render('doc/heart_disease.rmd')"`

```
# Rscript -e "rmarkdown::render('doc/heart_disease.rmd')"
Error in yaml::yaml.load(..., eval.expr = TRUE) :
  Scanner error: while scanning a simple key at line 10, column 3 could not find expected ':' at line 12, column 1
Calls: <Anonymous> ... parse_yaml_front_matter -> yaml_load -> <Anonymous>
Execution halted
```

```
# Rscript -e "rmarkdown::render('doc/heart_disease.rmd')"


processing file: heart_disease.rmd
Error in parse_block(g[-1], g[1], params.src, markdown_mode) :
  Duplicate chunk label 'correlation', which has been used for the chunk:
knitr::include_graphics("../results/varaible_correlation.png")
Calls: <Anonymous> ... process_file -> split_file -> lapply -> FUN -> parse_block
Execution halted
```
