### ISSUE TITLE
Milestone 4 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-2#140]
*Congratulations on finishing your final project!!! This is a great accomplishment and you should be proud!
Below we list some specific feedback you can use to improve your project if you so desire,
but most importantly to learn.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Addressed feedback given by the teaching team from milestone 1

- [ ] 10% or less of the feedback given by the teaching team from milestone 2 was not addressed **-2.5**

The feedback point for release repo link was not fully addressed.

### Addressed feedback given by the teaching team from milestone 2

- [ ] 10% or less of the feedback given by the teaching team from milestone 2 was not addressed **-2.5**

The reproducibility feedback points were not fully addressed

### Functional software package was created to share 3-4 functions that were written for the data analysis project.

- [ ] **(No points taken)** In `DSCI-310-Group-2-packages/R/balance_check.R`

```
library(rlang)
library(tidyverse)
```

### The software package is well documented

- [ ] It is missing vignette/tutorials docs. **- 1**

### The software package is robust (i.e., contains software tests for all package functions)

- [ ] There was no attempt. **- 5**

### Continous deployment is used to automate the building of the package documentation

- [ ] There was no attempt. **- 5**

### Dependencies have been updated (so it include the newly created external software package)

- [ ] Dependencies have been updated but are not in the final image. **- 0.5**

See "Analysis can be run reproducibly using documentation provided in the README" for more details

### Project file and directory structure organization

- [ ] There are folder/files that should not be committed. **- 0.5**

`.ipynb_checkpoints/`

### GitHub release

- [ ] Please provide the link to the release as `https://github.com/DSCI-310/REPOSITORY/tree/VERSION` (replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone). This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-.5**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] I got an error while trying to run `docker pull rpeng35/dsci-310_group_2:v0.25.0`. **- 2.5**

The rest of the analysis was based on the latest version

```
[giuseppett@fedora ~]$ docker pull rpeng35/dsci-310_group_2:v0.25.0
Error response from daemon: manifest for rpeng35/dsci-310_group_2:v0.25.0 not found: manifest unknown: manifest unknown
```

- [ ] I got an error while trying to run `make all`. **- 2.5**

You are missing your group package.

```
# make all
Rscript src/preprocess_data.r --input=data/raw/cleveland_raw.csv --out_dir=data/processed
── Attaching packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.1 ──
✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.6     ✔ dplyr   1.0.8
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1
── Conflicts ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
Warning messages:
1: package ‘tidyr’ was built under R version 4.1.2
2: package ‘readr’ was built under R version 4.1.2
3: package ‘dplyr’ was built under R version 4.1.2
Warning message:
package ‘docopt’ was built under R version 4.1.2
── Attaching packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidymodels 0.1.4 ──
✔ broom        0.7.12     ✔ rsample      0.1.1
✔ dials        0.1.0      ✔ tune         0.2.0
✔ infer        1.0.0      ✔ workflows    0.2.6
✔ modeldata    0.1.1      ✔ workflowsets 0.2.1
✔ parsnip      0.2.1      ✔ yardstick    0.0.9
✔ recipes      0.2.0
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()
• Learn how to get started at https://www.tidymodels.org/start/
Warning messages:
1: package ‘broom’ was built under R version 4.1.2
2: package ‘dials’ was built under R version 4.1.2
3: package ‘parsnip’ was built under R version 4.1.2
4: package ‘recipes’ was built under R version 4.1.2
5: package ‘tune’ was built under R version 4.1.2
6: package ‘workflows’ was built under R version 4.1.2
7: package ‘workflowsets’ was built under R version 4.1.2
Registered S3 method overwritten by 'GGally':
  method from
  +.gg   ggplot2

Attaching package: ‘rlang’

The following objects are masked from ‘package:purrr’:

    %@%, as_function, flatten, flatten_chr, flatten_dbl, flatten_int,
    flatten_lgl, flatten_raw, invoke, splice

Warning message:
package ‘rlang’ was built under R version 4.1.2

Attaching package: ‘magrittr’

The following object is masked from ‘package:rlang’:

    set_names

The following object is masked from ‘package:purrr’:

    set_names

The following object is masked from ‘package:tidyr’:

    extract

Warning message:
package ‘magrittr’ was built under R version 4.1.3
Error in library(group2) : there is no package called ‘group2’
Execution halted
make: *** [Makefile:11: data/processed/training.csv] Error 1
```

- [ ] Your docker environment is missing dependencies
