### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-2#3]
*Congratulations on finishing milestone 1! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### GitHub release

- [ ] Please provide the link to the release as `https://github.com/DSCI-310/REPOSITORY/tree/VERSION`
(replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone).
This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-1**

### README.md file

- [ ] Dependencies (or link pointing to list elsewhere) is missing from the `README.md` file. **-1**

### Analysis (`.ipynb`) file

- [ ] This document should not actually be named `analysis.ipynb`, but have a more descriptive title, related to the project title. **-1**

### Analysis methods & results

- [ ] Narration of methods and method choices was not as clear and thorough as expected. **-1**

### Dockerfile

- [ ] The base image the `Dockerfile` uses in the `FROM` statement should have it's version pinned.
Failing to do this, means that each time the Docker image is built in the future,
the latest version of the base image will be used.
The latest version of the base image will very likely change over time,
and failing to do this will lead to the container not being able to be reproducibly built in the future. **-1**

### Project organization

- [ ] The analysis notebook (`*.ipynb`) should be in a sub-directory called something sensible, such as `analysis`,
`src`, `notebooks`, `docs`, etc, to aid in the discoverability of this file, and related ones.
Having too many files in the project root makes the project organization less understandable
and can lead to longer activation times to productivity for collaborators (including future you!). **-1**

### GitHub Project board

- [ ] Project board was not used for the entire duration of the milestone. **-1**
- [ ] Project board is most effective when cards are converted to issues so that they can be assigned to collaborators, labelled and linked to milestones. **-1**

### GitHub Issue Milestones

- [ ] GitHub issue milestones were not used. **-5**

### CONTRIBUTING.md

- [ ] Contributing documentation should reflect all the ways people can contribute to the project
(core members, who should be working in a GitHub flow workflow involving branching in the main project repo and opening PR's,
as well as arms-length contributors, who more likely may have to fork the repo before submitting a PR). **-1**

### License

- [ ] Creative commons license needs to be included to specify how non-code/software work can be used, shared and derived. **-2**

### Follows GitHub flow version control workflow

- [ ] Project is expected to follow a GitHub flow version control workflow, which requires all branches to be divided into independent units of work (e.g., `feat-draft-analysis` for new feature which is the draft of the analysis, `fix-useage-docs` for some bug fix to the usage documentation) **-1**
- [ ] All contributions are expected to go through code review via a pull-request. **-2**
- [ ] Branching in the core team's project repository is the expected workflow, not forking.
If forking is being done, it is OK, as long as work in the fork is on branches. **-1**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] Clearly specify usage instructions to the point a user could copy and paste them and they would work.
If a specific value needs to be inserted (e.g., volume mounting, port forwarding, tag version - which should be specified, as relying on `latest` is unreliable for many reasons, etc)
suggest the most reasonable value and provide the list
(or link to a list) of alternative options. **-2**
- [ ] Could not reproducibly run the analysis because a package was missing from the provided computational environment. **-5**
