### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-2#32]
*Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Code is abstracted to functions with good function design

- [ ] Functions do not follow a consistent style. **-1**

`clean_data` has `}` indented whereas `accuracy_plot` does not. `clean_data` uses `::` whereas `accuracy_plot` uses `library(tibble)`.

### Functions are well documented

- [ ] One or more documentations could be improved through additional proofreading (i.e., spelling and grammatical errors are present). **- 0.5**

`clean_data`

- [ ] One or more functions are only partially understood from reading their documentation. **- 0.5**

`diagnosis` - it is not clear from the function documentation that the data frame must have a column named `diagnosis`. If the function is used on a data frame without that name, the function would break and the error would not be that helpful. Either the documentation needs to make this clearer, or the function should be redesigned to make the function more general (work on any specified column). 

### The functions work as expected (tests and analysis will tell us this)

- [ ] One of the functions failed when executing the analysis. **- 3**

Check `attribute_box_plots` in the "Analysis can be run reproducibly using documentation provided in the README" section

### Helper data for tests is tractable and reproducible

- [ ] There are cases of tests that recreate the output manually instead of using simple known input and output. **-1**

`accuracy_plot` recreates some plots for known output, which is not robust.

### Tests are written for each function, and work expected

- [ ] I got multiple errors while trying to run the tests. The error is not associated to a particular test, it is rather associated to the test suite itself. **- 5**

I tried running `Rscript -e "testthat::test_dir('tests')"` and got the following error

```
✔ | F W S  OK | Context
✖ | 1       0 | testthat
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error (testthat.R:2:1): (code run outside of `test_that()`)
Error in `library(DSCI - 310 - Group - 2)`: 'package' must be of length 1
Backtrace:
 1. base::library(DSCI - 310 - Group - 2) testthat.R:2:0
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

══ Results ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 0 ]
Error: Test failures
In addition: Warning message:
package ‘testthat’ was built under R version 4.1.2
Execution halted
```

Alternatively, I tried running `Rscript tests/testthat.R` and got the following error

```
Warning message:
package ‘testthat’ was built under R version 4.1.2
Error in library(DSCI - 310 - Group - 2) : 'package' must be of length 1
Execution halted
```
There are problems in running the test ruite due to code like `library(DSCI-310-Group-2)` and `test_check("DSCI-310-Group-2")`. I had to comment them out and try different commands to get the test suite running.

### Tests are well documented

- [ ] Test and/or helper files do not following best practices for filenames **-1**

In some cases, capitalization for full words in filenames is used, when all lower case is the best practice.

### Tests suite is of high quality

- [ ] There are cases of functions that do not test at least 1 edge-case input. **- 1**

`accuracy_plot`

- [ ] There are cases of tests that only look at some properties instead of comparing known output known to the output obtained from known input. **- 1**

The tests for `diagnosis` only test for the type and correct dimensions of the data frame that is returned, not the correct values (i.e., if a value is > 0, that a 1 is the value in that place in the returned data frame).

### GitHub Project board

- [ ] Project board is most effective when cards are converted to issues so that they can be assigned to collaborators, labeled and linked to milestones. **- 1**

### GitHub Issue Milestones

- [ ] There is a GitHub milestone for milestone 2 but it was not used. **- 1**

### GitHub release

- [ ] Please provide the link to the release as https://github.com/DSCI-310/REPOSITORY/tree/VERSION (replacing REPOSITORY and VERSION with the correct ones for your project version for each milestone). This makes a lot easier for someone to just visit the repository as it was at that point in the project's history. **-1**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] Project is almost inreproducible. **- 10**

Most importantly, there seems to have been some significant issues combining the code bases, leading to `attribute_box_plots.R` and `diagnosis.R` being missing from `R`, the tests for the functions those files contain being missing from `tests` and also them not being used in `Predicting_Heart_Disease.ipynb`. Digging into your repo, we were able to see pull requests where these were proposed and used the last commits before merging in those pull requests to grade those functions and tests (commit with attribute_box_plots function: https://github.com/DSCI-310/DSCI-310-Group-2/tree/ada69d74ed7e16c26540e1801b9e2e0bcde4a8da and
commit with diagnosis function: https://github.com/DSCI-310/DSCI-310-Group-2/tree/2f8bbfdb96f5c8bf4ea2a5f498f1be87adf71859). This was very challening for us. And these not being present in the submitted milestone version meant we could not run your entire analysis. 

Additionaly, there were other reproducibility errors, which we describe below:

There is no repository inside the container the docker command is probably lacking a `-v` argument.

There is no copy-paste instruction for cloning the repository.

On top of that, there are problemns in running the analysis due to code like `source("../R/attribe_box_plots.r")` which does not point to the correct location. Even after correcting it, I got the following error.

```
Error in attribute_box_plots(heart_disease_numerical, diagnosis): `col_b` should be an unquoted string
Traceback:

1. attribute_box_plots(heart_disease_numerical, diagnosis)
2. stop("`col_b` should be an unquoted string")
```
